runtime: python27
api_version: 1
service: frontend-app-1
threadsafe: true
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build


skip_files:
- ^(static/.*)
- ^(node_modules/.*)
- ^(public/.*)
- ^(scripts/.*)
